
INSERT INTO pages (slug, title, content, metadata, is_published, created_at)
VALUES
('about', 'About — KF8FVD', '<h2>Hi — I\'m Zachary (KF8FVD)</h2>\n<p>Technician-class ham operator in Kentwood, MI — radio, digital modes, and maker projects.</p>\n<div>\n  <p>By day, I work as a CNC and EDM Specialist in the aerospace and automotive industries. I have a deep passion for precision machining and anything technical. When I\'m not at the mill or the lathe, I am usually at my workbench tinkering with electronics, 3D printing, or hobbyist networking.</p>\n  <h3>The Shack &amp; Gear</h3>\n  <p>I am currently a Technician class operator with a heavy focus on the intersection of traditional RF and modern digital modes. My current setup includes:</p>\n  <ul>\n    <li>Handhelds: Icom ID-52A PLUS and a Baofeng DM-32UV.</li>\n    <li>Digital Setup: Active on D-STAR and DMR. I recently built a custom duplex MMDVM hotspot using a Raspberry Pi 4 running WPSD to stay connected globally from my home office.</li>\n  </ul>\n  <h3>Current Projects &amp; Goals</h3>\n  <p>I am actively studying for my General Class license and look forward to getting my first HF station on the air soon. Aside from radio, you can usually find me:</p>\n  <ul>\n    <li>Designing and printing parts on my Bambu Lab X1-C Carbon (Blender / Shaper3D).</li>\n    <li>Managing my home lab, including an Ubuntu server and Pi-hole for network-wide ad blocking.</li>\n    <li>Building custom PCs and exploring new tech.</li>\n  </ul>\n  <h3>QSL Information</h3>\n  <p>QRZ Logbook — updated regularly. eQSL — available.</p>\n  <p>If we\'ve just had a QSO via a reflector or local repeater, thanks for the contact! I look forward to catching you on the air again soon.</p>\n  <p>73, Zachary (KF8FVD)</p>\n</div>', '{"summary":{"title":"Hi — I am Zachary (KF8FVD)","text":"Technician-class ham operator in Kentwood, MI — radio, digital modes, and maker projects.","cta":{"label":"Contact Me","href":"/contactme"}},"cards":[{"title":"About Me","subtitle":"KF8FVD","content":"<p>73 from KF8FVD! Thanks for stopping by my QRZ page! My name is Zachary, and I am operating out of Kentwood, Michigan (near Grand Rapids).</p><h3>About Me</h3><p>By day, I work as a CNC and EDM Specialist in the aerospace and automotive industries. I have a deep passion for precision machining and anything technical. When I am not at the mill or the lathe, I am usually at my workbench tinkering with electronics, 3D printing, or hobbyist networking.</p>","image":"/headshot.jpg"},{"title":"Home Topology","subtitle":"Hidden Lakes Apartments, Kentwood","content":"","image":"/apts.jpg"},{"title":"Ham Shack","subtitle":"Home Radio & Workshop","content":"","image":"/hamshack.jpg"}]}', 1, NOW()) AS new_row
-- Seed data for `pages` table
-- Safe to run multiple times: uses ON DUPLICATE KEY UPDATE to avoid duplicates

INSERT INTO pages (slug, title, content, metadata, is_published, created_at)
VALUES
('about', 'About — KF8FVD', '<h2>Hi — I\'m Zachary (KF8FVD)</h2>\n<p>Technician-class ham operator in Kentwood, MI — radio, digital modes, and maker projects.</p>', '{"summary":{"title":"Hi — I\'m Zachary (KF8FVD)","text":"","cta":{"label":"Contact Me","href":"/contactme"}},"cards":[]}', 1, NOW()) AS new_row
ON DUPLICATE KEY UPDATE
  title = new_row.title,
  content = new_row.content,
  metadata = new_row.metadata,
  is_published = new_row.is_published,
  updated_at = NOW();
