#!/usr/bin/env node
const fs = require('fs')
const path = require('path')

// Simple repo-wide scanner for `dangerouslySetInnerHTML` occurrences.
// Usage: node tools/nonce-sweep.js > nonce-scan.txt

function walk(dir, files=[]) {
  const entries = fs.readdirSync(dir, { withFileTypes: true })
  for (const e of entries) {
    if (e.name === 'node_modules' || e.name === '.next' || e.name === '.git') continue
    const full = path.join(dir, e.name)
    if (e.isDirectory()) walk(full, files)
    else files.push(full)
  }
  return files
}

const root = path.resolve(__dirname, '..')
const files = walk(root)
const matches = []
for (const file of files) {
  if (!file.endsWith('.tsx') && !file.endsWith('.ts') && !file.endsWith('.jsx') && !file.endsWith('.js') && !file.endsWith('.html')) continue
  if (file.includes(path.sep + 'node_modules' + path.sep) || file.includes(path.sep + '.next' + path.sep)) continue
  const text = fs.readFileSync(file, 'utf8')
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].includes('dangerouslySetInnerHTML') || (lines[i].includes('<style') && lines[i].includes('dangerouslySetInnerHTML')) || lines[i].includes("nonce={")) {
      matches.push({ file: path.relative(root, file), line: i+1, snippet: lines[i].trim().slice(0,200) })
    }
  }
}

if (matches.length === 0) {
  console.log('No occurrences found')
  process.exit(0)
}

console.log('# Nonce Sweep Report')
console.log('\nGenerated by tools/nonce-sweep.js')
console.log('\nFound ' + matches.length + ' matches:\n')
for (const m of matches) {
  console.log(`- ${m.file} : L${m.line} -> ${m.snippet}`)
}

console.log('\n---\nSuggested next steps:')
console.log('- For server components that render <script type="application/ld+json"> or <style> tags: make the component async, read `const nonce = (await cookies()).get("csp-nonce")?.value` and set `nonce={nonce}` on the <script>/<style> tags.')
console.log('- For client components: ensure sanitized HTML does not include <script> or <style>; if it does, move JSON-LD or styles into server-rendered head or external files.')
console.log('- Create a PR with per-file small changes; avoid auto-modifying client components.')
